import React, {Component} from "react";

export default class Statutory_Audit_Corporate extends Component{
    constructor(props){
        super(props);
        this.fnAddRow = this.fnAddRow.bind(this);
        this.fnDeleteRow = this.fnDeleteRow.bind(this);
    }

    fnAddRow(e) {
        var tr = e.target.parentNode.parentNode.parentNode.nextElementSibling.firstChild.cloneNode(true);;
        e.target.parentNode.parentNode.parentNode.nextElementSibling.appendChild(tr);
    }
    fnDeleteRow(e){
        var len = e.target.parentNode.parentNode.parentNode.nextElementSibling.children.length;
        if(len != 1){
            e.target.parentNode.parentNode.parentNode.nextElementSibling.lastChild.remove();
        } else {alert("Please remove entire table by selection")}
    }

    render(){
        return(
         <div className="text-justify" style={{pageBreakBefore:"always",fontSize:20 }} contentEditable="true" suppressContentEditableWarning={true}>
            <h3 className="text-center">Independent Auditor’s Report</h3><br />
            <p>To the Members of {this.props.signInfo.ClientName}</p>
            <h5>Report on the Audit of the Standalone Financial Statements</h5>
            <div>
            <h5>Opinion</h5>
            <p>We have audited the financial statements of {this.props.signInfo.ClientName} (“the Company”), which comprise the balance sheet as at 31st March {this.props.signInfo.YearClose}, and the statement of Profit and Loss and statement of cash flows for the year then ended, and notes to the financial statements, including a summary of significant accounting policies and other explanatory information.<br />In our opinion and to the best of our information and according to the explanations given to us, the aforesaid financial statements give the information required by the Act in the manner so required and give a true and fair view in conformity with the accounting principles generally accepted in India, of the state of affairs of the Company as at 31st March, {this.props.signInfo.YearClose}, its profit/loss and its cash flows for the year ended on that date.</p> <br/><span>Or</span><br/>
            <h5>Qualified Opinion </h5>
            <p>We have audited the standalone financial statements of {this.props.signInfo.ClientName} (“the Company”), which comprise the balance sheet as at 31st March {this.props.signInfo.YearClose}, and the statement of Profit and Loss, and the statement of cash flows for the year then ended, and notes to the financial statements, including a summary of significant accounting policies and other explanatory information.
            In our opinion and to the best of our information and according to the explanations given to us, except for the effects of the matter described in the Basis for Qualified Opinion section of our report, the aforesaid financial statements give a true and fair view in conformity with the accounting principles generally accepted in India, of the state of affairs of the Company as 31st March {this.props.signInfo.YearClose} and profit/loss, and its cash flows for the year ended on that date. </p> <br/><span>Or</span><br/>
            <h5>Adverse Opinion </h5>
            <p>We have audited the accompanying financial statements of {this.props.signInfo.ClientName} (“the Company”), which comprise the balance sheet as at 31st March {this.props.signInfo.YearClose}, and the statement of Profit and Loss, and the statement of cash flows for the year then ended, and notes to the financial statements, including a summary of significant accounting policies and other explanatory information.<br />In our opinion and to the best of our information and according to the explanations given to us, because of the significance of the matter discussed in the Basis for Adverse Opinion section of our report, the accompanying financial statements do not give a true and fair view in conformity with the accounting principles generally accepted in India as at 31st March {this.props.signInfo.YearClose}, of its profit/loss and the cash flows for the year then ended. </p> <br/><span>Or</span><br/>
            <h5>Disclaimer of Opinion </h5>
            <p>We were engaged to audit the accompanying financial statements of {this.props.signInfo.ClientName} (hereinafter referred to as the “Holding Company”) and its subsidiaries (the Holding Company and its subsidiaries together referred to as “the Group), which comprise the consolidated balance sheet as at 31st March {this.props.signInfo.YearClose}, the consolidated statement of Profit and Loss, and consolidated statement of cash flows for the year then ended, and notes to the consolidated financial statements, including a summary of significant accounting policies (hereinafter referred to as the “Consolidated Financial Statements”).<br/> We do not express an opinion on the accompanying consolidated financial statements of the Group. Because of the significance of the matter described in the Basis for Disclaimer of Opinion section of our report, we have not been able to obtain sufficient appropriate audit evidence to provide a basis for an audit opinion on these consolidated financial statements.</p>
            </div>
            <div>
            <h5>Basis for Opinion</h5>
            <p>We conducted our audit in accordance with the Standards on Auditing (SAs) specified under section 143(10) of the Companies Act, 2013. Our responsibilities under those Standards are further described in the Auditor’s Responsibilities for the Audit of the Financial Statements section of our report. We are independent of the Company in accordance with the Code of Ethics issued by the Institute of Chartered Accountants of India together with the ethical requirements that are relevant to our audit of the financial statements under the provisions of the Companies Act, 2013 and the Rules thereunder, and we have fulfilled our other ethical responsibilities in accordance with these requirements and the Code of Ethics. We believe that the audit evidence we have obtained is sufficient and appropriate to provide a basis for our opinion.</p><br/><span>Or</span><br/>
            <h5>Basis for Qualified Opinion</h5>
            <p>The Company’s inventories are carried in the Balance Sheet at Rs. XXX. Management has not stated the inventories at the lower of cost and net realizable value but has stated them solely at cost, which constitutes a departure from the Accounting Standards prescribed under section 133 of the Companies Act, 2013. The Company’s records indicate that, had management stated the inventories at the lower of cost and net realizable value, an amount of Rs. xxx would have been required to write the inventories down to their net realizable value. Accordingly, cost of sales would have been increased by Rs. xxx, and income tax, net income and shareholders’ funds would have been reduced by Rs. xxx, Rs. xxx and Rs. xxx, respectively. <br/>We conducted our audit in accordance with Standards on Auditing (SAs) specified under section 143(10) of the Companies Act, 2013. Our responsibilities under those Standards are further described in the Auditor’s Responsibilities for the Audit of the Financial Statements section of our report. We are independent of the Company in accordance with the Code of Ethics issued by the Institute of Chartered Accountants of India together with the ethical requirements that are relevant to our audit of the financial statements under the provisions of the Companies Act, 2013 and we have fulfilled our other ethical responsibilities in accordance with these requirements and the ICAI’s Code of Ethics. We believe that the audit evidence we have obtained is sufficient and appropriate to provide a basis for our qualified opinion. .</p><br/><span>Or</span><br/>
            <h5>Basis for Adverse Opinion </h5>
            <p>As explained in Note X, the Group has not consolidated subsidiary XYZ Company that the Group acquired during 20XX because it has not yet been able to determine the fair values of certain of the subsidiary’s material assets and liabilities at the acquisition date. This investment is therefore accounted for on a cost basis. Under the accounting principles generally accepted in India, the Group should have consolidated this subsidiary and accounted for the acquisition based on provisional amounts. Had XYZ Company been consolidated, many elements in the accompanying consolidated financial statements would have been materially affected. The effects on the consolidated financial statements of the failure to consolidate have not been determined. <br/>We conducted our audit in accordance with Standards on Auditing (SAs) specified under section 143(10) of the Companies Act, 2013. Our responsibilities under those Standards are further described in the Auditor’s Responsibilities for the Audit of the Consolidated Financial Statements section of our report. We are independent of the Group, its associates and jointly controlled entities, in accordance with the Code of Ethics and provisions of the Companies Act, 2013 that are relevant to our audit of the consolidated financial statements in India under the Companies Act, 2013, and we have fulfilled our other ethical responsibilities in accordance with the Code of Ethics and the requirements under the Companies act, 2013. We believe that the audit evidence we have obtained is sufficient and appropriate to provide a basis for our adverse opinion. </p><br/><span>Or</span><br/>
            <h5>Basis for Disclaimer of Opinion </h5>
            <p>The Group’s investment in its joint venture XYZ Company is carried at Rs. xxx on the Group’s consolidated balance sheet, which represents over 90% of the Group’s net assets as at March 31, {this.props.signInfo.YearClose}. We were not allowed access to the management and the auditors of XYZ Company, including XYZ Company’s auditors’ audit documentation. As a result, we were unable to determine whether any adjustments were necessary in respect of the Group’s proportional share of XYZ Company’s assets that it controls jointly, its proportional share of XYZ Company’s liabilities for which it is jointly responsible, its proportional share of XYZ’s income and expenses for the year, and the consolidated cash flow statement.</p>
            </div>
            <h5>Information other than the financial statements and auditors’ report thereon</h5>
            <p>The Company’s board of directors is responsible for the preparation of the other information. The other information comprises the information included in the Board’s Report including Annexures to Board’s Report but does not include the financial statements and our auditor’s report thereon.<br />Our opinion on the financial statements does not cover the other information and we do not express any form of assurance conclusion thereon.<br />In connection with our audit of the financial statements, our responsibility is to read the other information and, in doing so, consider whether the other information is materially inconsistent with the financial statements or our knowledge obtained during the course of our audit or otherwise appears to be materially misstated.<br />If, based on the work we have performed, we conclude that there is a material misstatement of this other information, we are required to report that fact. We have nothing to report in this regard.</p>
            <h5>Going Concern Section</h5>
            <h5>Material Uncertainty Relating to Going Concern </h5>
            <p>We draw attention to <mark>Note 6</mark> in the financial statements, which indicates that the Company incurred a net loss of XXX during the year ended March 31, {this.props.signInfo.YearClose}. and, as of that date, the Company’s current liabilities exceeded its total assets by XXX. As stated in <mark>Note 6</mark>, these events or conditions, along with other matters as set forth in <mark>Note 6</mark>, indicate that a material uncertainty exists that may cast significant doubt on the Company’s ability to continue as a going concern. Our opinion is not modified in respect of this matter. </p>
            <h5>Going Concern Basis of Accounting </h5>
            <p><mark>The Company’s financial statements have been prepared using the going concern basis of accounting. Management is responsible for assessing the Company’s ability to continue as a going concern, including whether the use of the going concern basis of accounting is appropriate. The use of the going concern basis of accounting is appropriate unless management either intends to liquidate the Company or to cease operations, or has no realistic alternative but to do so. Management is also responsible for disclosing [in the financial statements] a material uncertainty of which management becomes aware related to events or conditions that may cast significant doubt on the Company’s ability to continue as a going concern.<br/>As part of our audit, we conclude regarding the appropriateness of management’s use of the going concern basis of accounting in the preparation of the financial statements in the context of the applicable financial reporting framework. We also conclude, based on the audit evidence obtained, whether a material uncertainty exists related to events or conditions that may cast significant doubt on the entity’s ability to continue as a going concern. If we conclude that a material uncertainty exists, we are required to draw attention in the auditor’s report to the disclosures in the financial statements about the material uncertainty or, if such disclosures are inadequate, to modify the opinion on the financial statements. Our conclusions are based on information available to us at the date of the auditor’s report. However, future events or conditions may cause an entity to cease to continue as a going concern.</mark></p>
            <h5>Emphasis of Matter</h5>
            <p>We draw attention to Note X of the financial statements, which describes the effects of a …………... in the Company’s facilities. Our opinion is not modified in respect of this matter.</p>
            <h5>Key Audit Matters </h5>
            <p>Key audit matters are those matters that, in our professional judgment, were of most significance in our audit of the financial statements of the current period. These matters were addressed in the context of our audit of the financial statements as a whole, and in forming our opinion thereon, and we do not provide a separate opinion on these matters. (*applicable only in case of listed companies/companies in which disclaimer of opinion is not made)</p><br /><span>or</span><br />
            <p>Key audit matters are those matters that, in our professional judgment, were of most significance in our audit of the financial statements of the current period. These matters were addressed in the context of our audit of the financial statements as a whole, and in forming our opinion thereon, and we do not provide a separate opinion on these matters. In addition to the matter described in the Basis for Qualified Opinion section we have determined the matters described below to be the key audit matters to be communicated in our report: (*applicable only in case of listed companies) </p><br /><span>or</span><br />
            <p>Except for the matter described in the Basis for Adverse Opinion section, we have determined that there are no other key audit matters to communicate in our report.</p>
            <h5>Responsibilities of Management and Those Charged with Governance for the Standalone Financial Statements</h5>
            <p>The Company’s Board of Directors is responsible for the matters stated in section 134(5) of the Companies Act, 2013 (“the Act”) with respect to the preparation of these financial statements that give a true and fair view of the financial position, financial performance and cash flows of the Company in accordance with the accounting principles generally accepted in India, including the accounting Standards specified under section 133 of the Act. This responsibility also includes maintenance of adequate accounting records in accordance with the provisions of the Act for safeguarding of the assets of the Company and for preventing and detecting frauds and other irregularities; selection and application of appropriate accounting policies; making judgments and estimates that are reasonable and prudent; and design, implementation and maintenance of adequate internal financial controls, that were operating effectively for ensuring the accuracy and completeness of the accounting records, relevant to the preparation and presentation of the financial statements that give a true and fair view and are free from material misstatement, whether due to fraud or error. <br />
                In preparing the financial statements, management is responsible for assessing the Company’s ability to continue as a going concern, disclosing, as applicable, matters related to going concern and using the going concern basis of accounting unless management either intends to liquidate the Company or to cease operations, or has no realistic alternative but to do so.<br/>
                Those Board of Directors are also responsible for overseeing the Company’s financial reporting process.</p>
            <h5>Auditor’s Responsibilities for the Audit of the Financial Statements</h5>
            <p>Our objectives are to obtain reasonable assurance about whether the financial statements as a whole are free from material misstatement, whether due to fraud or error, and to issue an auditor’s report that includes our opinion. Reasonable assurance is a high level of assurance, but is not a guarantee that an audit conducted in accordance with SAs will always detect a material misstatement when it exists. Misstatements can arise from fraud or error and are considered material if, individually or in the aggregate, they could reasonably be expected to influence the economic decisions of users taken on the basis of these financial statements.<br/>
                As part of an audit in accordance with SAs, we exercise professional judgment and maintain professional skepticism throughout the audit. We also: <br/>
            <ul><li>Identify and assess the risks of material misstatement of the financial statements, whether due to fraud or error, design and perform audit procedures responsive to those risks, and obtain audit evidence that is sufficient and appropriate to provide a basis for our opinion. The risk of not detecting a material misstatement resulting from fraud is higher than for one resulting from error, as fraud may involve collusion, forgery, intentional omissions, misrepresentations, or the override of internal control.</li>
            <li>Obtain an understanding of internal control relevant to the audit in order to design audit procedures that are appropriate in the circumstances. Under section 143(3)(i) of the Companies Act, 2013, we are also responsible for expressing our opinion on whether the company has adequate internal financial controls system in place and the operating effectiveness of such controls.</li>
            <li>Evaluate the appropriateness of accounting policies used and the reasonableness of accounting estimates and related disclosures made by management.</li>
            <li>Conclude on the appropriateness of management’s use of the going concern basis of accounting and, based on the audit evidence obtained, whether a material uncertainty exists related to events or conditions that may cast significant doubt on the Company’s ability to continue as a going concern. If we conclude that a material uncertainty exists, we are required to draw attention in our auditor’s report to the related disclosures in the financial statements or, if such disclosures are inadequate, to modify our opinion. Our conclusions are based on the audit evidence obtained up to the date of our auditor’s report. However, future events or conditions may cause the Company to cease to continue as a going concern.</li>
            <li>Evaluate the overall presentation, structure and content of the financial statements, including the disclosures, and whether the financial statements represent the underlying transactions and events in a manner that achieves fair presentation.</li></ul>
                We communicate with those charged with governance regarding, among other matters, the planned scope and timing of the audit and significant audit findings, including any significant deficiencies in internal control that we identify during our audit. <br/>
                We also provide those charged with governance with a statement that we have complied with relevant ethical requirements regarding independence, and to communicate with them all relationships and other matters that may reasonably be thought to bear on our independence, and where applicable, related safeguards. <br/>
                From the matters communicated with those charged with governance, we determine those matters that were of most significance in the audit of the financial statements of the current period and are therefore the key audit matters. We describe these matters in our auditor’s report unless law or regulation precludes public disclosure about the matter or when, in extremely rare circumstances, we determine that a matter should not be communicated in our report because the adverse consequences of doing so would reasonably be expected to outweigh the public interest benefits of such communication.<br /> <span>or</span><br />
                Our responsibility is to conduct an audit of the Group’s consolidated financial statements in accordance with Standards on Auditing and to issue an auditor’s report. However, because of the matter described in the Basis for Disclaimer of Opinion section of our report, we were not able to obtain sufficient appropriate audit evidence to provide a basis for an audit opinion on these consolidated financial statements. <br/>
                We are independent of the Group in accordance with the ethical requirements that are relevant to our audit of the financial statements and we have fulfilled our other ethical responsibilities in accordance with these requirements.</p>
            <h5>Report on Other Legal and Regulatory Requirements</h5>
            <ol><li>As required by the Companies (Auditor’s Report) Order, 2016 (“the Order”), issued by the Central Government of India in terms of sub-section (11) of section 143 of the Companies Act, 2013, we give in the ‘Annexure A’, a statement on the matters specified in paragraphs 3 and 4 of the Order, to the extent applicable.</li>
            <li>As required by Section 143 (3) of the Act, we report that:
            <ol type="a"><li>We have sought and obtained all the information and explanations which to the best of our knowledge and belief were necessary for the purposes of our audit.</li>
            <li>In our opinion, proper books of account as required by law have been kept by the Company so far as it appears from our examination of those books.</li>
            <li>The Balance Sheet, the Statement of Profit and Loss and the Cash Flow Statement dealt with by this Report are in agreement with the books of account.</li>
            <li>In our opinion, the aforesaid financial statements comply with the Accounting Standards specified under Section 133 of the Act, read with Rule 7 of the Companies (Accounts) Rules, 2014. </li>
            <li>On the basis of the written representations received from the directors as on 31st March, {this.props.signInfo.YearClose} taken on record by the Board of Directors, none of the directors is disqualified as on 31st March, {this.props.signInfo.YearClose} from being appointed as a director in terms of Section 164 (2) of the Act.</li>
            <li>With respect to the adequacy of the internal financial controls over financial reporting of the Company and the operating effectiveness of such controls, refer to our separate Report in ‘Annexure B’. </li>
            <li>With respect to the other matters to be included in the Auditor’s report in accordance with the requirements of Sec 197(16) of the Act as amended, we report that Section 197 is not applicable to a private company. Hence reporting as per Section 197(16) is not required. (applicable in case of Private Company)<br  /><span>or</span><br />
                With respect to the matter to be included in the Auditor’s Report under section 197(16), In our opinion and according to the information and explanations given to us, the remuneration paid by the Company to its directors during the current year is in accordance with the provisions of section 197 of the Act. The remuneration paid to any director is not in excess of the limit laid down under section 197 of the Act. The Ministry of Corporate Affairs has not prescribed other details under section 197(16) which are required to be commented upon by us. (applicable in case of Public Company)</li>
            <li>With respect to the other matters to be included in the Auditor’s Report in accordance with Rule 11 of the Companies (Audit and Auditors) Rules, 2014, in our opinion and to the best of our information and according to the explanations given to us:
            <ol type="i"><li>The Company does not have any pending litigations which would impact its financial position.<br/><span>or</span><br/>
                The Company has disclosed pending litigations and the impact on its financial position - refer note _______ to the Standalone Financial Statements.</li>
            <li>The Company did not have any long-term contracts including derivative contracts for which there were any material foreseeable losses. <br/><span>or</span><br/>
                The Company has made provision, as required under the applicable law or accounting standards, for material foreseeable losses, if any, on long-term contracts including derivative contracts;</li>
            <li>There were no amounts which were required to be transferred to the Investor Education and Protection Fund by the Company. <br/><span>or</span><br/>
                There has been no delay in transferring amounts, required to be transferred, to the Investor Education and Protection Fund by the Company. <br/><span>or</span><br/>
                Following are the instances of delay in transferring amounts, required to be transferred, to the Investor Education and Protection Fund by the Company :……….</li></ol></li></ol></li></ol>
            <address>
                For {this.props.signInfo.FirmName} ,<br/>
                Chartered Accountants,<br />
                Firm Registration Number:{this.props.signInfo.FRN}.<br /><br /><br/>
                {this.props.signInfo.PartnerName},<br />
                Partner.<br />
                Membership No: {this.props.signInfo.MemberNo}.<br/>
                Udin: {this.props.signInfo.RepUdin},<br/><br/>
                Place: {this.props.signInfo.Place},<br/>
                Date: {this.props.signInfo.SignDate}.
            </address>
            <div style={{pageBreakBefore:"always"}}>
            <h5 className="text-right">Annexure ‘A’</h5>
            <h5>The Annexure referred to in paragraph 1 of Our Report on “Other Legal and Regulatory Requirements”.</h5>
            <p>We report that:</p>
            <ol type="i"><li><ol type="a"><li>The company has maintained proper records showing full particulars, including quantitative details and situation of its fixed assets.</li>
            <li>As explained to us, fixed assets have been physically verified by the management at reasonable intervals; no material discrepancies were noticed on such verification.</li>
            <li>The title deeds of immovable properties are held in the name of the company. </li></ol></li>
            <li>As explained to us, inventories have been physically verified during the year by the management at reasonable intervals. No material discrepancy was noticed on physical verification of stocks by the management as compared to book records.</li>
            <li>The company has granted loans to ………parties covered in the register maintained under section 189 of the Companies Act, 2013.
            <ol type="a"><li>The terms and conditions of the grant of such loans are not prejudicial to the company’s interest;</li>
            <li>The schedule of repayment of principal and payment of interest has been stipulated and in such cases the borrowers have been regular in repayment of principal and interest.<br /><span>or</span><br />
                The terms of arrangement do not stipulate any repayment schedule and the loans are repayable on demand with interest.</li>
            <li>There are no overdue amounts in respect of the loans granted to the parties listed in the register maintained under section 189 of the Act. .<br /><span>or</span><br />
                Since the term of arrangement do not stipulate any repayment schedule and the loans are repayable on demand, no question of overdue amounts will arise in respect of the loans granted to the parties listed in the register maintained under section 189 of the Act. .<br /><span>or</span><br />
                Amounts are overdue in respect of above loans. The total amount overdue for more than ninety days is……….and reasonable steps have been taken by the company for recovery of the principal and interest. .<br /><span>or</span><br />
                Amounts are overdue is respect of above loans. But there is no amounts overdue for more than ninety days. Reasonable steps have been taken by the company for recovery of the principal and interest.</li></ol>.<br /><span>or</span><br />
                According to the information and explanations given to us and on the basis of our examination of the books of account, the Company has not granted any loans, secured or unsecured, to companies, firms, Limited Liability Partnerships or other parties listed in the register maintained under Section 189 of the Companies Act, 2013.  Consequently, the provisions of clauses iii (a), (b) and (c)of the order are not applicable to the Company.</li>
            <li>In respect of loans, investments, guarantees, and security, provisions of section 185 and 186 of the Companies Act, 2013 have been complied with. .<br /><span>or</span><br />
                The company has complied with provisions of section 185 & 186 in respect of loans, investments, guarantees, and security except to the extent of: 
            <table className="table table-responsive table-bordered table-hover table-condensed" style={{pageBreakInside: "avoid"}}><thead><tr><th>S. No.</th><th> Non-compliance of Section 186</th><th> Name of Company/ Party </th><th> Amount Involved </th><th> Balance as at Balance Sheet Date </th><th> Remarks, if any </th></tr></thead>
            <tbody><tr><td>1</td><td>Investment through more than two layers of investment companies</td><td></td><td></td><td></td><td></td></tr>
            <tr><td>2</td><td> Loan given or guarantee given or security provided or acquisition of securities exceeding the limits without prior approval by means of a special resolution </td><td></td><td></td><td></td><td></td></tr>
            <tr><td>3</td><td>Loan given at rate of interest lower than prescribed </td><td></td><td></td><td></td><td></td></tr>
            <tr><td>4</td><td> Any other default </td><td></td><td></td><td></td><td></td></tr></tbody></table></li>
            <li>The company has not accepted any deposits from the public covered under sections 73 to 76 of the Companies Act, 2013 except Rs.xxx from ………… According to information and explanation provided to us, no order has been passed by Company Law Board or National Company Law Tribunal or Reserve Bank of India or any court or any other tribunal.<br /><span>or</span><br />
                The Company has not accepted any deposits from the public and hence the directives issued by the Reserve Bank of India and the provisions of Sections 73 to 76 or any other relevant provisions of the Act and the Companies (Acceptance of Deposit) Rules, 2015 with regard to the deposits accepted from the public are not applicable</li>
            <li>As per information and explanation given by the management, maintenance of cost records has not been specified by the Central Government under sub-section (1) of section 148 of the Companies Act, 2013.</li>
            <li><ol type="a"><li>According to the records of the company, undisputed statutory dues including Provident Fund, Investor Education and Protection Fund, Employees’ State Insurance, Income-tax, Sales-tax, Service Tax, Goods and Service tax, Custom Duty, Excise Duty, value added tax, cess and any other statutory dues to the extent applicable, have generally been regularly deposited with the appropriate authorities. According to the information and explanations given to us there were no outstanding statutory dues as on 31st March {this.props.signInfo.YearClose} for a period of more than six months from the date they became payable, except :
            <table className="table table-responsive table-bordered table-hover table-condensed"  style={{pageBreakInside: "avoid"}}><thead><tr><th>Name of the Statue</th><th>Nature of the Dues</th><th>Amount (Rs. In lakhs)</th><th>Period for which the amount relates</th><th>Due Date</th><th>Date of Payment</th><th> Remarks, if any <span className="btn" onClick={this.fnAddRow} >+</span> <span className="btn" onClick={this.fnDeleteRow}>-</span></th></tr></thead><tbody id="AddRow"><tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr></tbody></table></li>
            <li>According to the information and explanations given to us, there is no amount payable in respect of income tax, service tax, sales tax, customs duty, excise duty, value added tax and cess whichever applicable, which have not been deposited on account of any disputes.<br /><span>or</span><br />
                According to the records of the Company, the dues outstanding of income-tax, sales-tax, service tax, goods and service tax, duty on custom, duty of excise, value added tax and cess on account of any dispute, are as follows:
                <table className="table table-responsive table-bordered table-hover table-condensed"  style={{pageBreakInside: "avoid"}}><thead><tr><th>Name of the Statue</th><th>Nature of the Dues</th><th>Amount (Rs. In lakhs)</th><th>Period for which the amount relates</th><th>Forum where dispute is pending <span className="btn" onClick={this.fnAddRow} >+</span> <span className="btn" onClick={this.fnDeleteRow}>-</span></th></tr></thead><tbody id="forumTable"><tr><td></td><td></td><td></td><td></td><td></td></tr></tbody></table></li></ol></li>
            <li>In our opinion and according to the information and explanations given by the management, we are of the opinion that, the Company has not defaulted in repayment of dues to a financial institution, bank, Government or debenture holders, as applicable to the company. </li>
            <li>Based on our audit procedures and according to the information given by the management, the company has not raised any money by way of initial public offer or further public offer (including debt instruments) or taken any term loan during the year.<br /><span>or</span><br />
            Based on our audit procedures and according to the information given by the management, the company has not raised any money by way of initial public offer or further public offer (including debt instruments) or taken any term loan during the year.</li>
            <li>According to the information and explanations given to us, we report that no fraud by the company or any fraud on the Company by its officers or employees has been noticed or reported during the year. </li>
            <li>The company is a private limited company. Hence the provisions of clause (xi) of the order are not applicable to the company. .<br /><span>or</span><br />
            According to the information and explanations given to us, we report that managerial remuneration has been paid in accordance with the requisite approvals mandated by the provisions of section 197 read with Schedule V to the Companies Act.</li>
            <li>The company is not a Nidhi Company. Therefore, clause (xii) of the order is not applicable to the company. .<br /><span>or</span><br />
            The Nidhi Company has complied with the Net Owned Funds to Deposits in the ratio of 1: 20 to meet out the liability and the Nidhi Company is maintaining ten per cent unencumbered term deposits as specified in the Nidhi Rules, 2014 to meet out the liability.</li>
            <li>According to the information and explanations given to us, all transactions with the related parties are in compliance with sections 177 and 188 of Companies Act, 2013 where applicable and the details have been disclosed in the Financial Statements etc. as required by the applicable accounting standards.</li>
            <li>The company has not made any preferential allotment or private placement of shares or fully or partly convertible debentures during the year under review. .<br /><span>or</span><br />
            The company has made preferential allotment or private placement of shares or fully or partly convertible debentures during the year under review and the requirement of section 42 of the Companies Act, 2013 have been complied with and the amount raised have been used for the purposes for which the funds were raised. </li>
            <li>Provisions of section 192 of Companies Act, 2013 have been complied with in case of non-cash transactions entered by the company with directors or persons connected with him. .<br /><span>or</span><br />
            The company has not entered into non-cash transactions with directors or persons connected with him.</li>
            <li>The company is not required to be registered under section 45-IA of the Reserve Bank of India Act, 1934. .<br /><span>or</span><br />
            The company is required to be registered under section 45-IA of the Reserve Bank of India Act, 1934 and the registration has been obtained.</li></ol>
            <address>
                For {this.props.signInfo.FirmName} ,<br/>
                Chartered Accountants,<br />
                Firm Registration Number:{this.props.signInfo.FRN}.<br /><br /><br/>
                {this.props.signInfo.PartnerName},<br />
                Partner.<br />
                Membership No: {this.props.signInfo.MemberNo}.<br/>
                Udin: {this.props.signInfo.RepUdin},<br/><br/>
                Place: {this.props.signInfo.Place},<br/>
                Date: {this.props.signInfo.SignDate}.
            </address>
            </div>
            <div style={{pageBreakBefore:"always"}}>
            <h5 className="text-right">Annexure ‘B’</h5>
            <h5>Report on the Internal Financial Controls under Clause (i) of Sub-section 3 of Section 143 of the Companies Act, 2013 (“the Act”)</h5>
            <p>We have audited the internal financial controls over financial reporting of {this.props.signInfo.ClientName} (“the Company”) as of March 31, {this.props.signInfo.YearClose} in conjunction with our audit of the  financial statements of the Company for the year ended on that date.</p>
            <h5>Management’s Responsibility for Internal Financial Controls</h5>
            <p>The Company’s management is responsible for establishing and maintaining internal financial controls based on the internal control over financial reporting criteria established by the Company considering the essential components of internal control stated in the Guidance Note on Audit of Internal Financial Controls Over Financial Reporting issued by the Institute of Chartered Accountants of India. These responsibilities include the design, implementation and maintenance of adequate internal financial controls that were operating effectively for ensuring the orderly and efficient conduct of its business, including adherence to company’s policies, the safeguarding of its assets, the prevention and detection of frauds and errors, the accuracy and completeness of the accounting records, and the timely preparation of reliable financial information, as required under the Companies Act, 2013.</p>
            <h5>Auditors’ Responsibility</h5>
            <p>Our responsibility is to express an opinion on the Company's internal financial controls over financial reporting based on our audit. We conducted our audit in accordance with the Guidance Note on Audit of Internal Financial Controls Over Financial Reporting (the “Guidance Note”) and the Standards on Auditing, issued by ICAI and deemed to be prescribed under section 143(10) of the Companies Act, 2013, to the extent applicable to an audit of internal financial controls, both applicable to an audit of Internal Financial Controls and, both issued by the Institute of Chartered Accountants of India. Those Standards and the Guidance Note require that we comply with ethical requirements and plan and perform the audit to obtain reasonable assurance about whether adequate internal financial controls over financial reporting was established and maintained and if such controls operated effectively in all material respects.<br />
            Our audit involves performing procedures to obtain audit evidence about the adequacy of the internal financial controls system over financial reporting and their operating effectiveness. Our audit of internal financial controls over financial reporting included obtaining an understanding of internal financial controls over financial reporting, assessing the risk that a material weakness exists, and testing and evaluating the design and operating effectiveness of internal control based on the assessed risk. The procedures selected depend on the auditor’s judgement, including the assessment of the risks of material misstatement of the financial statements, whether due to fraud or error.<br />
            We believe that the audit evidence we have obtained is sufficient and appropriate to provide a basis for our audit opinion on the Company’s internal financial controls system over financial reporting.</p>
            <h5>Meaning of Internal Financial Controls Over Financial Reporting</h5>
            <p>A company's internal financial control over financial reporting is a process designed to provide reasonable assurance regarding the reliability of financial reporting and the preparation of financial statements for external purposes in accordance with generally accepted accounting principles. A company's internal financial control over financial reporting includes those policies and procedures that 
            <ol><li>pertain to the maintenance of records that, in reasonable detail, accurately and fairly reflect the transactions and dispositions of the assets of the company;</li>
            <li>provide reasonable assurance that transactions are recorded as necessary to permit preparation of financial statements in accordance with generally accepted accounting principles, and that receipts and expenditures of the company are being made only in accordance with authorisations of management and directors of the company; and</li>
            <li>provide reasonable assurance regarding prevention or timely detection of unauthorized acquisition, use, or disposition of the company's assets that could have a material effect on the financial statements.</li></ol></p>
            <h5>Inherent Limitations of Internal Financial Controls Over Financial Reporting</h5>
            <p>Because of the inherent limitations of internal financial controls over financial reporting, including the possibility of collusion or improper management override of controls, material misstatements due to error or fraud may occur and not be detected. Also, projections of any evaluation of the internal financial controls over financial reporting to future periods are subject to the risk that the internal financial control over financial reporting may become inadequate because of changes in conditions, or that the degree of compliance with the policies or procedures may deteriorate.</p>
            <h5>Opinion</h5>
            <p>In our opinion, the Company has, in all material respects, an adequate internal financial controls system over financial reporting and such internal financial controls over financial reporting were operating effectively as at March 31, {this.props.signInfo.YearClose}, based on the internal control over financial reporting criteria established by the Company considering the essential components of internal control stated in the Guidance Note on Audit of Internal Financial Controls Over Financial Reporting issued by the Institute of Chartered Accountants of India.</p>
            <address>
                For {this.props.signInfo.FirmName} ,<br/>
                Chartered Accountants,<br />
                Firm Registration Number:{this.props.signInfo.FRN}.<br /><br /><br/>
                {this.props.signInfo.PartnerName},<br />
                Partner.<br />
                Membership No: {this.props.signInfo.MemberNo}.<br/>
                Udin: {this.props.signInfo.RepUdin},<br/><br/>
                Place: {this.props.signInfo.Place},<br/>
                Date: {this.props.signInfo.SignDate}.
            </address>
            </div>
         </div>
        )
    }
}